### ISSUE TITLE
MapWarper WMS images blocked by Chrome

### ISSUE THREAD

**Issue by waynegraham** [performant-software/Neatline#403] opened 2016-12-02 13:48 UTC
Ran in to an issue with adding a WMS resource to a map. With the Open Street Map base map selected, adding a WMS map with these values produces notices that the content was blocked by the client:

**WMS Address**: http://mapwarper.net/maps/wms/9937
**WMS Layers**: StonewallJacksonCemetery

(the layer name shouldn't actually matter for MapServer requests).

In the console debug, this tile comes back with a `(failed)` status (sometimes registers as `BLOCKED BY CLIENT`):

[http://mapwarper.net/maps/wms/9937?LAYERS=StonewallJacksonCemetery&TRANSPARENT=TRUE&FORMAT=image%2Fpng&TILED=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8843791.2973073,4548524.6785611,-8843638.4232507,4548677.5526176&WIDTH=256&HEIGHT=256](http://mapwarper.net/maps/wms/9937?LAYERS=StonewallJacksonCemetery&TRANSPARENT=TRUE&FORMAT=image%2Fpng&TILED=true&SERVICE=WMS&VERSION=1.1.1&REQUEST=GetMap&STYLES=&SRS=EPSG%3A900913&BBOX=-8843791.2973073,4548524.6785611,-8843638.4232507,4548677.5526176&WIDTH=256&HEIGHT=256)

This doesn't appear to be the case with WMS coming out of Geoserver (tested with `http://gis.lib.virginia.edu/geoserver/wms` and `McGregor:000003093_00011`). 

These layers appear as expected in Firefox (50.0.1) and Safari (10.0.1).

**Comment by erochest** [comment] 2016-12-02 19:20
Thanks for the warning. I'll see if I can sort through this (and some other tickets here) next week.

**Comment by jamiefolsom** [comment] 2017-04-07 15:52
Hi @jeremyboggs, I am not able to reproduce this specific issue of tile images being blocked by Chrome. Can you confirm one way or the other? I am using the latest release of Chrome, version 57.0.2987.133 (There remains an issue with WMS maps, served by mapwarper, when they're specified in an exhibit rather than in a record, which I am working on.) Thanks!

**Comment by timwaters** [comment] 2017-04-07 16:42
Note that a couple of days ago Mapwarper.net was updated to allow CORS for map requests based on another JS library encountering problems with it, but I don't know if thats related

**Comment by jamiefolsom** [comment] 2017-04-07 16:44
@timwaters thanks for the heads up! Could have been related; might also have been caused by an issue in an earlier release of Chrome. I am not seeing the issue now, myself.

**Comment by jamiefolsom** [comment] 2017-06-21 16:24
Closed by #413

**Closed as completed by jamiefolsom** 2017-06-21 16:24 UTC
Labels: defect, priority-high
