### ISSUE TITLE
Can't link Item to Omeka (only with certain items)

### ISSUE THREAD

**Issue by aliasonline** [performant-software/Neatline#354] opened 2015-03-12 20:07 UTC
I'm using Omeka 2.2.2 and Neatline 2.4 (with no other neatline plugins installed).

I have a very strange error with Neatline (error also occurred with v2.3). 
Whenever I try to link a record to an Omeka item, I get an error message after 10 seconds or so: "There was an error - the record was not saved"

The error seems to occur only with Omeka items that have attached files (files have to visible). The error doesn't occur if an item doesn't have any attached file or the attached file is not visible like this one (http://geosciencecollections.milne-library.org/items/show/609).
- Here is an item with an error when trying to link to Omeka (http://geosciencecollections.milne-library.org/items/show/667)
- Here is an item without an error when trying to link to Omeka (http://geosciencecollections.milne-library.org/items/show/609)

Any help will be very appreciated. Thank you.

**Comment by waynegraham** [comment] 2015-03-14 14:34
Thanks for letting us know about this @aliasonline. We'll take a look and get this resolved.

**Comment by erochest** [comment] 2015-03-16 18:54
Hi @aliasonline , Sorry that Neatline is giving you trouble. Could you tell me what other plugins you have installed? That might help us track down exactly what's going on here.

Thanks

**Comment by aliasonline** [comment] 2015-03-16 19:00
Here are other installed plugins:

Collection Tree Version 2.0.1
CSV Import Version 2.0.2 
Dropbox Version 0.7.2
Dublin Core Extended Version 2.0.1
Exhibit Builder Version 3.1.1
Geolocation Version 2.2.1
Item Order Version 2.0.1
Search By Metadata Version 1.2
Simple Pages Version 3.0.1
Simple Vocab Version 2.0.1

**Comment by erochest** [comment] 2015-03-16 19:50
Thanks. I'll check these out.

**Comment by erochest** [comment] 2015-03-17 16:55
I'm working through these plugins, but it would also be helpful if we could get more information about your error. There are two things you could do:
1. If you have access to the server, you can look through the server log to see if there's a PHP error listed there.
2. If you're using Chrome or Firefox, open the JavaScript console (in Chrome, that's menu View > Developer > JavaScript Console; in FF, it's Tools > Web Developer > Web Console). Try linking the item that displays the error, and see if anything prints in the console. What does it say? (There may be nothing, but it's worth a shot.)

**Comment by aliasonline** [comment] 2015-03-17 19:47
I don't have access to the server but I ran tests using JavaScript Console in Chrome. 

Here is the Network log for successful save:
![successfully-saved](https://cloud.githubusercontent.com/assets/176336/6696064/bbb66cf2-ccbc-11e4-9d83-5d7301fb7d8e.png)

Here is the Network log for UNsuccessful save:
![error-saving](https://cloud.githubusercontent.com/assets/176336/6696082/e796950e-ccbc-11e4-8647-c53a9287dd55.png)

**Comment by davidmcclure** [comment] 2015-03-17 20:33
Hey @aliasonline,

Does everything seem to work correctly up until you hit the save button? For example, when you click on the Omeka item in the drop down select, does the Dublin Core load into the blue preview box?

Also, let's try this - when you hit the error, click on the listing in the Network tab for the failed request, scroll down to the "Request Payload" section in the "Header" tab, and paste in the parameters here (or send them to the Neatline support address, if there's any private information on the record).

I can't reproduce this directly, but I do notice something not-ideal about how Neatline is forming the requests to save the item. The HTML from the Omeka item is getting threaded into the request that goes back to the server (this should be fixed, either way), and I wonder if there might be some kind of non-standard markup or characters in the item HML that's breaking things on the server.

Thanks!

**Comment by aliasonline** [comment] 2015-03-20 16:48
Yes, the Dublin Core loads into the blue preview box. Here is the link to the parameters: https://gist.github.com/aliasonline/f185c916a5f370242e83

FYI. I tried with a newly created item that only has minimum information (ie: title) but that one didn't work either.

**Comment by aliasonline** [comment] 2015-03-30 17:55
I was wondering about the status of the issue. Any updates, please?

**Comment by erochest** [comment] 2015-03-30 19:31
I haven't been able to reproduce this yet, and unfortunately I've gotten pulled off onto some other things. I'll try to free up some more time this week to dig into it further.

**Comment by erochest** [comment] 2015-04-08 20:53
I'm still unable to reproduce this. So let me ask a few more questions.

Do you know anything about how your server is set up? We've had issues with mod_security before, and disabling that has worked for some people.

**Comment by davidmcclure** [comment] 2015-04-10 04:15
Hey @aliasonline,

Ok, I just pushed up a change that fixes the issue that I think might be responsible for this problem. I'm not sure, since I can't replicate the problem directly, but this is my best guess.

I know you said that you don't have access to the server, but is there any way you could get someone who does to install the [bug/item-serialization](https://github.com/scholarslab/Neatline/tree/bug/item-serialization) branch, and see if this fixes the problem? If not, this change will get folded into the next official release.

**Comment by aliasonline** [comment] 2015-04-10 13:27
I can FTP to the server. Which files need to be updated?

**Comment by davidmcclure** [comment] 2015-04-10 21:55
You should just need to update the [neatline-editor.js](https://github.com/scholarslab/Neatline/blob/bug/item-serialization/views/shared/javascripts/dist/production/neatline-editor.js) file:

`views/shared/javascripts/dist/production/neatline-editor.js`

**Comment by aliasonline** [comment] 2015-04-13 20:07
Thank you, David. It's working now!

**Comment by davidmcclure** [comment] 2015-04-13 21:42
Great - we'll include the fix in the next release.

**Closed as completed by davidmcclure** 2015-04-13 21:42 UTC
Labels: defect

**Comment by waynegraham** [comment] 2015-04-14 12:35
In d9eb375ce2020b82a0f1be6993dbf929a7aae091

**Comment by waynegraham** [comment] 2015-04-14 12:37
@davidmcclure Is this merged in to the develop branch?

**Comment by davidmcclure** [comment] 2015-04-14 17:43
Just merged it.
