### ISSUE TITLE
Simile timeline not responding to "hard link" URLs

### ISSUE THREAD

**Issue by astrohm** [performant-software/Neatline#355] opened 2015-03-17 14:06 UTC
In the release documentation for Neatline 2.3, there's mention of a new "hard link" capability. I've had success linking to a particular record in a Neatline exhibit, but I'm not seeing the Simile timeline scrolling, as the Scholar's Lab release announcement (http://scholarslab.org/announcements/neatline-2-3/) indicates it should.

For example, if I have a record that has a set of after/before dates set as 1900 and 1999, when I link to the record using the #records/recordnumber URL, the map's zoom and focus is adjusted correctly, but the exhibit loads at the default date (2015), meaning that this record isn't visible on the map. Is this a bug, or did I misunderstand the way that this function works?

I've sent the URL to Wayne (as the site's still in development, I didn't want to post it here), along with an example record.

**Comment by waynegraham** [comment] 2015-03-17 19:06
Could we get a list of plugins that you have enabled also? We've seen some odd conflicts recently...

**Comment by astrohm** [comment] 2015-03-17 20:15
Sure -- 

Dublin Core Extended
Neatline
Neatline - Similie
Neatline - Waypoints
Simple Pages

We've got a few other plugins installed but not activated (Clean URL, Exhibit Builder, COins)

**Comment by davidmcclure** [comment] 2015-03-17 21:00
Yep, I'm seeing this on my local machine. I think this is what's happening:
- Neatline starts up, reads the record id in the URL fragment, loads the record, and fires the `select` event with a Backbone model for the record.
- SIMILE waits until _after_ the main Neatline application is running to start (see [here](https://github.com/scholarslab/nl-widget-Simile/blob/master/views/shared/javascripts/public/simile.init.js#L14-L20)). This is because (as @astrohm notes) SIMILE applies a visibility filter to the map, and so it needs to wait until the map is running and populated with content before applying the filter.

But, this also means that the SIMILE controller isn't running when the initial `select` event gets fired from the router, so the timeline doesn't apply the selection.

This could be tricky to fix. The best approach, I think, would be to find a way to start SIMILE normally with the rest of the application, and then have the router wait until the entire application is running before firing the `select` event. I think this would work:
- Get rid of the `startWithParent: false` flags in the SIMILE widget, which will allow the plugin to start automatically with the parent application.
- In the SIMILE controller, listen for the `MAP:ingest` event, which gets fired when a batch of records is loaded. When this first fires, apply the time filter.
- In Neatline, don't start the `Events` module with the parent - wait until the global `initialize:after` event fires (like SIMILE does now).

**Comment by erochest** [comment] 2015-05-14 18:38
Fixed this in a61cc0de2aac3aa6bbd7bd5178c3031b01b9b096 and scholarslab/nl-widget-Simile@1eff7c11b7f79ab531c8c7b012ff7696d3c026ba. Should be able to release next, assuming I can get the tests working.

**Comment by astrohm** [comment] 2015-06-24 14:24
I got curious and attempted to make the changes in a61cc0d to app.init.js and events.init.js, but don't see any change in functionality. I assume the tests directory in the Simile commit is a dev-only thing, since I don't see it in my installation of Simile?

**Comment by erochest** [comment] 2015-06-24 14:39
Right. We have a set of tests under that directory that will automatically test various parts of our code. We can run the tests and quickly see whether something's broken. The system's not perfect, but it helps a lot.

**Comment by astrohm** [comment] 2015-06-24 15:14
That's what I figured. So to enable the proper hard-linking functionality on my site, all I should need to do is make the changes in a61cc0d?

**Comment by erochest** [comment] 2015-06-25 19:33
Not quite. Those files get compiled into another file. That's the one that will need to change. You'll also need to make the changes at nl-widget-Simile@ddfa76bb6c8421dbf81c76cbc6ebeaebffb60a94, including in the compiled files.

But it will be easier to just upgrade to the latest version of both of these plugins. I've just uploaded to the Omeka plugin directory [Neatline 2.4.1](http://omeka.org/add-ons/plugins/neatline/) and [NeatlineSimile 2.0.3](http://omeka.org/add-ons/plugins/neatlinesimile/).

Those should take care of this issue.

**Comment by astrohm** [comment] 2015-06-25 19:53
Great, thanks!

**Comment by erochest** [comment] 2015-06-26 13:20
Verified still not fixed.

**Comment by erochest** [comment] 2015-07-06 19:29
Just for the record, I cannot reproduce this either locally on your site, @astrohm (because the computer gods hate me). I'm going to leave this open a while longer and check it again. If I still can't reproduce it, I'll close it until there is another sighting.

**Comment by astrohm** [comment] 2015-07-09 16:49
Interestingly, things have been working as expected in the few weeks since I updated Neatline. I'll let you know if the Simile problems resurface.

**Comment by erochest** [comment] 2015-07-09 16:52
Great. Keep us posted.

I suspect that there may have been some caching issue with either Apache or PHP that meant you were still serving the old version of Neatline for a while longer. But let's keep an eye on it for a bit.

Thanks

**Comment by erochest** [comment] 2015-07-20 15:50
I tried to replicate this again, but I'm still unable to. I'm going to go ahead and close this.

But if this is still happening to anyone else, please reopen it.

**Comment by dlacy** [comment] 2015-08-18 20:28
I find the functionality described here to work in Simile and Neatline, except in situations where Simile defines a simile_default_date - in which case the timeline always places itself on the default date, ignoring the date referenced in the hard-linked record.

**Comment by erochest** [comment] 2015-08-18 20:38
Thanks for the report.

**Comment by astrohm** [comment] 2015-08-18 21:16
That's odd -- I don't have a default date set for Simile, but I'm still experiencing this problem again after the last Simile/Neatline updates.

**Comment by dlacy** [comment] 2015-08-18 23:09
@astrohm Are you testing against the official releases or the masters?

**Comment by astrohm** [comment] 2015-08-19 13:59
I'm testing against the official releases.

**Comment by dlacy** [comment] 2015-08-19 18:10
Removing the timeout on the "setCenterDate" invocation solves my problem, though I am uncertain of further repercussions in doing so.

https://github.com/scholarslab/nl-widget-Simile/blob/master/views/shared/javascripts/public/simile.view.js#L98

**Comment by erochest** [comment] 2015-08-19 19:35
Well, I think it will probably now ignore the default date, if you do set one.

Thanks for working it out this far, though. That'll help when I dig into it further.

**Comment by dlacy** [comment] 2015-08-19 19:41
I believe it now works as expected. For clarity, I only removed the timeout, not the call to:

_this.setCenterDate(date);

**Comment by erochest** [comment] 2015-08-19 19:46
The timeout is there because of issues loading. When you have the date set on an item, it won't scroll all the way to the date without it. You can see the commit at https://github.com/scholarslab/nl-widget-Simile/commit/7485b9af8a41d0f1400aa94b7c0b4560631ebd31 .

**Comment by jeremyboggs** [comment] 2018-05-10 13:04
This was addressed in NeatlineSimile.

**Closed as completed by jeremyboggs** 2018-05-10 13:04 UTC
Labels: defect, needs-review
