### ISSUE TITLE
Zoom ability on Google base layers does not match zoom ability on Google Maps

### ISSUE THREAD

**Issue by rondauva** [performant-software/Neatline#424] opened 2017-07-06 18:46 UTC
Testing for a user today, realized that I could zoom much further in when looking at the Google Street layer on Google Maps than I can when using Google Street as a base layer for a Neatline exhibit.

We've have multiple requests to allow for zoom levels that pick up all available granularity, usually as the result of georectifying an historic or hand drawn map of a city block or a cemetary and then overlaying that on a google layer as a neatline item. If the feature that's been added as a neatline item requires the map to be zoomed further in that we're apparently allowing, the map layer in the item isn't viewable.

Does Neatline restrict the zoom levels? Or is this imposed by Google for apps that are loading its base layers via api?

(assigning to everyone. you can sort yourselves out.)

**Comment by akstuhl** [comment] 2017-07-07 20:59
Neatline does set a hard-coded limit for zoom levels on certain layer types; that value could be changed, but reading this issue alongside #295 makes me think it'd be worth adding a couple fields to the exhibit settings to provide a general solution for zoom constraints. PR #310 makes changes along these lines, but may be behind the master branch by far enough at this point that a fresh start would be warranted. Does this issue / feature addition seem appropriate for inclusion in the 2.6.0 milestone?

**Comment by jcmundy** [comment] 2017-11-02 18:13
I am using Omeka 2.5.1 and Neatline 2.6.0.  I am getting the error ```ReferenceError: google is not defined```  in neatline-editor.js for the admin edit side of any Neatline exhibit using Google as a base-map.  Any other base-map works fine.  The map will display on the public view (but without a center point and without any entries, because I cannot edit it).  Our site is hosted on Dreamhost.  This is new since I updated to 2.6.0.  Thank you for any help!

**Comment by jamiefolsom** [comment] 2017-11-02 18:20
Hi @jcmundy, thank you for this report. Could you provide a screenshot of the exhibit settings page, minus any proprietary or sensitive info? Any other info you can offer, like PHP and MySQL versions, other plugins installed, etc, might help too.

**Comment by jcmundy** [comment] 2017-11-02 18:43
![screen shot 2017-11-02 at 2 23 38 pm](https://user-images.githubusercontent.com/15927765/32343341-8576802e-bfd9-11e7-8eba-54441297b7cd.png)
![screen shot 2017-11-02 at 2 22 35 pm](https://user-images.githubusercontent.com/15927765/32343348-87e982c0-bfd9-11e7-9574-90ff19f6fe61.png)
Here is how I set a new exhibit.

**Comment by jcmundy** [comment] 2017-11-02 18:48
Here is the public exhibit that I have up at: http://ecdsdev.org/oakland/neatline/show/test-google 
![screen shot 2017-11-02 at 2 47 19 pm](https://user-images.githubusercontent.com/15927765/32344312-d4f887ca-bfdc-11e7-891a-ef4f7ef6798e.png)

**Comment by jamiefolsom** [comment] 2017-11-02 19:00
Thank you, @jcmundy. I will see if I can reproduce this, and get back to you.

**Comment by jcmundy** [comment] 2017-11-06 18:02
Also, I went back in and added a point to the public map http://ecdsdev.org/oakland/neatline/show/test-google   I added the point by changing the base layer to OpenStreetMap and then back to google satellite after.   The point looks normal at first, but if you zoom in to the largest satellite view, the point moves independently of the background map tiles.

**Comment by jcmundy** [comment] 2017-11-17 15:02
Does the geolocation plugin cause problems with the Neatline plugin?  They both use a google code.  Also, does it cause problems to have old Neatline folders (from past installs) still (renamed) in the plugins folder?  I just installed the update, and I'm still having google-base-map-specific issues.

**Comment by jamiefolsom** [comment] 2017-11-17 15:47
@jcmundy You're right, that both plugins have a config field for a google maps API token, but if the geolocation plugin is present, and has a token in place, Neatline will use that one. 

That said, if geolocation is installed, but incorrectly configured, that could cause problems for Neatline.

If possible, would you confirm that geolocation is either not installed, or else installed and correctly configured with a valid google maps API token?

Thanks!

**Comment by jcmundy** [comment] 2017-11-17 15:55
I have had it installed.  Today I deactivated it to see if that would help with the Google zoom issue, which remained unchanged after the new install.  It is currently deactivated.

**Comment by jcmundy** [comment] 2017-11-17 15:56
I can reactivate it.

**Comment by jamiefolsom** [comment] 2017-11-17 16:01
So if geolocation is deactivated, you would need to put a google maps API token into the neatline configuration. See: http://your.omeka-domain.org/admin/plugins/config?name=Neatline

**Comment by jcmundy** [comment] 2017-11-17 16:02
I have.  It continues to say "Google is not defined."  Thank you for your help!

**Comment by jcmundy** [comment] 2017-11-17 16:07
For comparision, here is a map with google-base:  http://ecdsdev.org/oakland/neatline/show/test-google
Here is a map with Stamen: http://ecdsdev.org/oakland/neatline/show/here-is-the-exhibit

**Comment by jamiefolsom** [comment] 2017-11-17 16:12
Thanks, @jcmundy we're taking a look

**Comment by akstuhl** [comment] 2017-11-20 19:27
Hi @jcmundy, thanks to your documentation here we've been able to reproduce the 'google not defined' bug and identified a fix — as you suggested, Neatline's interaction with the Geolocation plugin is faulty in certain cases. This leads to the error when Geolocation was installed but deactivated and when viewing an exhibit in the editor interface. I've opened a separate issue at #445 to address this problem specifically, so we'll close this issue for now and continue discussion there. Thanks!

**Closed as completed by akstuhl** 2017-11-20 19:27 UTC
Labels: needs-review

**Comment by jcmundy** [comment] 2017-11-21 19:01
Hi @akstuhl  Thank you for this!  This does fix my error with back-end editing on google maps!  I am still having a weird issue exhibit when I am using the google maps, though.  When zoomed in to the maximum zoom, points move at a different ratio to the background map.  The points themselves appear to stop scaling at the previous maximum zoom.  You can see the issue here: http://ecdsdev.org/oakland/neatline/show/test-google   Thank you again.

**Comment by akstuhl** [comment] 2017-11-21 19:26
Hi @jcmundy, very glad to hear you were able to fix the error! We've addressed the behavior at high zoom level in Google layers in #443 — that fix as well as the one for the interaction with Geolocation will be included in the next release, which we're in the process of preparing.

**Comment by jcmundy** [comment] 2017-11-21 19:27
Thanks!  I appreciate the help.
